baseURL = "https://112books.github.io/awpcp.org/"
title = "A.W.P.C.P."
locale = "ca"
DefaultContentLanguage = "ca"
disableLanguages = []
enableGitInfo = false

[params]
  description = "Around the World's Pinhole Crazy People — Worldwide Pinhole Photography Day"
  author = "Alfonso de Castro & Joan Linux"
  email = "info@awpcp.org"
  instagram = "https://www.instagram.com/aroundworldpinholecrazypeople/"
  facebook = "https://www.facebook.com/awpcp.org/"
  ogImage = "img/awpcp-logo.png"
  latestEdition = "2026"
  goatcounter = "awpcp"
  pinholeDayDate = "2026-04-26T11:00:00"

[languages]
  [languages.ca]
    locale = "ca"
    label = "CA"
    weight = 1
    contentDir = "content"
    [languages.ca.params]
      description = "Around the World's Pinhole Crazy People — Dia Mundial de la Fotografia Estenopeica"
  [languages.en]
    locale = "en"
    label = "EN"
    weight = 2
    contentDir = "content"
    [languages.en.params]
      description = "Around the World's Pinhole Crazy People — Worldwide Pinhole Photography Day"
  [languages.es]
    locale = "es"
    label = "ES"
    weight = 3
    contentDir = "content"
    [languages.es.params]
      description = "Around the World's Pinhole Crazy People — Día Mundial de la Fotografía Estenopeica"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[permalinks]
  editions = "/:slug/"
  editions_cameras = "/:slug/"

[outputs]
  home = ["HTML", "RSS"]
  section = ["HTML", "RSS"]
  page = ["HTML"]

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[mediaTypes]
  [mediaTypes."text/netlify"]
    suffix = ""

[outputFormats]
  [outputFormats.NETLIFY]
    mediaType = "text/netlify"
    baseName = "_redirects"
    isPlainText = true
    notAlternative = true

[minify]
  disableCSS = false
  disableHTML = false
  disableJS = false
  disableJSON = false
  disableSVG = false
  disableXML = false
  minifyOutput = true
  [minify.tdewolff]
    html = { keepWhitespace = false }
